name: run tests

on:
  push:
    branches: [main, dev]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          yarn install
      - name: Test
        run: yarn test