name: run tests

on:
  push:
    branches: [main, dev]

jobs:
  install_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          yarn install
      - name: Build
        run: yarn build
      - name: Download circom Binary v2.1.0
        run: |
          mkdir -p /home/runner/.local/bin
          wget -qO /home/runner/.local/bin/circom https://github.com/iden3/circom/releases/download/v2.1.0/circom-linux-amd64
          chmod +x /home/runner/.local/bin/circom
      - name: Test Typescript implementations
        run: yarn test:ts
      - name: Test class implementation
        run: yarn test:class 
      - name: Test Circom circuits
        run: yarn test:circom